<?php

$score = 0;
echo $score;
echo "<br>";
$voornaam ="Tom";
$voornaam1 ="Tomm";
$voornaam2 ="Tommm";
$voornaam3 ="Tommmm";
echo $voornaam;
echo "<br>";
$leeftijd = 24;
$melk = 0.88;
echo $leeftijd," ","$" , $melk;
$test = true;
echo "<br>";
echo $test;
$test ;
echo $test;
gettype($voornaam);
echo gettype($voornaam);
echo "<br>";
echo gettype($leeftijd);
echo gettype($melk);
echo gettype($test);
$null = null;
echo gettype($null);
echo "Jouw naam is " . $voornaam . " en je bent " . $leeftijd . " jaar oud.";
echo "<li>$voornaam1</li><li>$voornaam2</li><li>$voornaam3</li>";
$item = "<li>tas</li>";
$item .= "<li>bal</li>";
$item .= "<li>voet</li>";
echo $item;
var_dump($test);
echo 'Mijn leeftijd is $leeftijd';
$myMovies = ["Spiderman", "Batman", "The Joker"];
foreach($myMovies as $movies) {
	echo $movies;
	echo '<br>';
};
$myHeroesNames =  ['tijger', 'mickey', 'tijger'];
echo $myHeroesNames[0];
echo $myHeroesNames[1];
echo $myHeroesNames[2];
$myHeroesNames[1] = 'panter';
echo $myHeroesNames[1];
echo "<br>";
$myHeroesNames[3] = "jamiro";
array_push($myHeroesNames, "silver");
print_r($myHeroesNames);